import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SideBar from "@/components/SideBar";
import AuthProvider from "@/context/AuthProvider";
import { getServerSession } from "next-auth/next";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGpt Clone",
  description: "Generated by Brian",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className}`}>
        <AuthProvider>
          <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
            {/* SideBar */}
            <SideBar />
          </div>
          {/* ClientProvider - Notification */}
          <main className="bg-[#343541] flex-1">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
