import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGpt Clone",
  description: "Generated by Brian",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className}`}>
        {/* SideBar */}
        <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
          <SideBar />
        </div>
        {/* ClientProvider - Notification */}
        <main className="bg-[#343541] flex-1">{children}</main>
      </body>
    </html>
  );
}
